import streamlit as st

# Set page config
st.set_page_config(
    page_title="WAF Assessment Dashboard",
    layout="wide",
    initial_sidebar_state="collapsed"
)

# Dashboard configuration - AUTO-GENERATED BY DEPLOYMENT
INSTANCE_URL = "https://dbc-2a8b378f-7d51.cloud.databricks.com"
DASHBOARD_ID = "01f102495b341fd2a36ed55be09cb1f2"
WORKSPACE_ID = "2a8b378f7d51"
EMBED_URL = f"{INSTANCE_URL}/embed/dashboardsv3/{DASHBOARD_ID}?o={WORKSPACE_ID}"

# Title
st.title("🔍 WAF Assessment Dashboard")
st.markdown("---")

# Embed the dashboard
st.components.v1.iframe(EMBED_URL, height=800, scrolling=True)

st.markdown("---")
st.caption("💡 Databricks WAF Assessment Dashboard - Automated Well-Architected Framework Analysis")
st.caption(f"Dashboard ID: {DASHBOARD_ID} | Workspace: {WORKSPACE_ID}")
