command: [
  "streamlit",
  "run",
  "app.py"
]
env:
  - name: WAF_CATALOG
    value: "<<your_catalog>>"
  - name: WAF_JOB_ID
    value: "<<set_by_installer>>"
  - name: WAF_WAREHOUSE_ID
    value: "<<set_by_installer>>"
  - name: WAF_GENIE_URL
    value: "<<set_by_installer>>"
  - name: WAF_INSTANCE_URL
    value: "<<set_by_installer>>"
  - name: WAF_DASHBOARD_ID
    value: "<<set_by_installer>>"
  - name: WAF_WORKSPACE_ID
    value: "<<set_by_installer>>"
